### ISSUE TITLE
Error while persisting update to disk: The system cannot find the path specified

### ISSUE THREAD

**Issue by Benzilla** [meilisearch/firestore-meilisearch#137]
**Description**
When adding a document to my Firestore indexed collection locally in the Firestore emulator, I'm met with this error:

```
i  functions: Beginning execution of "indexingWorker"
>  {"location":"us-central1","collectionPath":"Users","meilisearch":{"host":"http://127.0.0.1:7700/","apiKey":"","indexUid":"users","fieldsToIndex":""},"severity":"INFO","message":"Started execution of extension with configuration"}
>  {"severity":"INFO","message":"Creating new document kGMFTdfL8WZdgu7KyRld in Meilisearch index: users"}
>  {"severity":"ERROR","message":"Unhandled error occurred during processing: class_1 [MeiliSearchApiError]: An internal error has occurred. `Error while persisting update to disk: The system cannot find the path specified. (os error 3) at path \"C:\\\\dev\\\\servers\\\\my-project\\\\./data.ms\\\\updates/updates_files\\\\.tmpJSQCV5\"`.\n    at C:\\Users\\my-name\\.cache\\firebase\\extensions\\meilisearch\\firestore-meilisearch@0.1.9\\functions\\node_modules\\meilisearch\\dist\\bundles\\meilisearch.cjs.js:169:23\n    at step (C:\\Users\\my-name\\.cache\\firebase\\extensions\\meilisearch\\firestore-meilisearch@0.1.9\\functions\\node_modules\\meilisearch\\dist\\bundles\\meilisearch.cjs.js:86:23)\n    at Object.next (C:\\Users\\my-name\\.cache\\firebase\\extensions\\meilisearch\\firestore-meilisearch@0.1.9\\functions\\node_modules\\meilisearch\\dist\\bundles\\meilisearch.cjs.js:67:53)\n    at fulfilled (C:\\Users\\my-name\\.cache\\firebase\\extensions\\meilisearch\\firestore-meilisearch@0.1.9\\functions\\node_modules\\meilisearch\\dist\\bundles\\meilisearch.cjs.js:57:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5) {\n  code: 'internal',\n  type: 'internal',\n  link: 'https://docs.meilisearch.com/errors#internal',\n  httpStatus: 500\n}"}
>  {"severity":"INFO","message":"Completed execution of extension"}
i  functions: Finished "indexingWorker" in 5.1447ms
```

**Expected behavior**
The document gets indexed successfully within the emulator without throwing any errors.

**Environment (please complete the following information):**
- OS: Windows 11
- Meilisearch version: [e.g. v.0.29.0]
- firestore-meilisearch version: [e.g v0.1.9]

**Comment by oluademola** [comment]
Hi @Benzilla. How did you configure the meilisearch extension in the Firestore emulator

**Comment by bidoubiwa** [comment]
Hey! I'm closing this issue as it is stale and missing information to be able to fix this issue.
Feel free to re-open it if it persists
